#############################################
# Picom config (no animations)
#############################################

backend = "glx";
vsync = true;

#############################################
# Transparency (DISABLED globally)
#############################################

active-opacity = 0.83;
inactive-opacity = 0.83;
frame-opacity = 0.80;
detect-client-opacity = true;

opacity-rule = [
  "100:class_g = 'Google-chrome'",
]

#############################################
# Blur
#############################################

# blur-method = "dual_kawase";
# blur-strength = 7;
# blur-background = true;
# blur-background-frame = true;

blur-background-exclude = [
  "class_g = 'Google-chrome'",
  "class_g = 'kitty'"
];

#############################################
# Shadows
#############################################

shadow = false;

#############################################
# Animations (DISABLED)
#############################################

fading = false;
fade-in-step = 0.0;
fade-out-step = 0.0;
no-fading-openclose = true;

#############################################
# General behavior
#############################################

detect-transient = true;
detect-client-leader = true;
