background_opacity 0.85
font_family AnonymicePro Nerd Font Mono
font_size        30

disable_ligatures never
cursor_shape underline
cursor #00FF00
scrollback_lines 10000
shell_integration no-cursor

enable_audio_bell no

foreground #00FF00
background #000000


color0  #000000
color1  #00FF00
color2  #00FF00
color3  #00FF00
color4  #00FF00
color5  #00FF00
color6  #00FF00
color7  #00FF00
color8  #00AA00
color9  #00FF00
color10 #00FF00
color11 #00FF00
color12 #00FF00
color13 #00FF00
color14 #00FF00
color15 #00FF00
