set -g base-index 1 # Windows start at 1
setw -g pane-base-index 1  # Panes start at 1

# Creates a new window in the same path
bind c new-window -c "#{pane_current_path}" 

# renumber windows
set-option -g renumber-windows on

# new panes in the same path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# cursor style
set -g cursor-style underline

# status bar goes on the top
set-option -g status-position top

set -g status-style bg=default
set -g status-left-style bg=default
set -g status-right-style bg=default

# Command/message area transparent
set -g message-style "bg=default"
set -g message-command-style "bg=default"

set -g window-status-current-format "• #I:#W"
set -g status-right '#(cd "#{pane_current_path}" && branch=$(git branch --show-current 2>/dev/null) && [ -n "$branch" ] && echo " $branch ⌇ ")#(whoami)@#H ⌇ #S ⌇ %H:%M'
set -g status-right-length 100
set -g status-left ""

set -g mouse on
setw -g mode-keys vi
