gui:
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  showBottomLine: false
  showPanelJumps: false
  showRandomTip: false
  showCommandLog: false
  showListFooter: false
  border: rounded
  animateExplosion: false
  filterMode: fuzzy
  mouseEvents: false
  expandFocusedSidePanel: true
  sidePanelWidth: 0.3
  language: en
  theme:
    activeBorderColor:
      - '#f5c2e7'
      - bold
    inactiveBorderColor:
      - '#6c7086'
    searchingActiveBorderColor:
      - '#89b4fa'
      - bold
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f5c2e7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
notARepository: skip
keybinding:
  universal:
    quit: 'q'
    return: '<esc>'
